repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: pnpm-lint
        name: pnpm lint
        entry: pnpm lint
        language: system
        types_or: [ts, tsx]
        pass_filenames: false
  - repo: local
    hooks:
      - id: pnpm-format
        name: pnpm format
        entry: pnpm format
        language: system
        types_or: [ts, tsx]
        pass_filenames: false
