import { describe, expect, it } from 'bun:test'
import type { CalendarEvent } from '@ilamy/calendar'
import dayjs from '@/utils/dayjs'
import { RRule } from 'rrule'
import { deleteRecurringEvent } from './delete-recurring-event'
import { generateRecurringEvents } from './generate-recurring-events'
import { updateRecurringEvent } from './update-recurring-event'

const createBaseRecurringEvent = (
	overrides: Partial<CalendarEvent> = {}
): CalendarEvent => ({
	id: 'event-1',
	title: 'Weekly Sync',
	start: dayjs('2025-01-06T10:00:00.000Z'),
	end: dayjs('2025-01-06T11:00:00.000Z'),
	rrule: {
		freq: RRule.WEEKLY,
		interval: 1,
		dtstart: new Date('2025-01-06T10:00:00.000Z'),
	},
	...overrides,
})

describe('recurring mutations', () => {
	describe('deleteRecurringEvent', () => {
		it('should delete entire series (scope: all) when uid is missing from base event', () => {
			const baseEvent = createBaseRecurringEvent({ id: 'series-1' })
			// Instance generated by the engine would have a generated UID
			const targetInstance: CalendarEvent = {
				...baseEvent,
				id: 'series-1_1',
				start: baseEvent.start.add(1, 'week'),
				end: baseEvent.end.add(1, 'week'),
				uid: 'series-1@ilamy.calendar',
				rrule: undefined,
			}

			const currentEvents = [baseEvent]
			const result = deleteRecurringEvent({
				targetEvent: targetInstance,
				currentEvents,
				scope: 'all',
			}).events

			expect(result).toHaveLength(0)
		})

		it('should delete entire series (scope: all) when uid is explicitly set', () => {
			const baseEvent = createBaseRecurringEvent({
				id: 'series-2',
				uid: 'custom-uid',
			})
			const targetInstance: CalendarEvent = {
				...baseEvent,
				id: 'series-2_1',
				start: baseEvent.start.add(1, 'week'),
				end: baseEvent.end.add(1, 'week'),
				uid: 'custom-uid',
				rrule: undefined,
			}

			const currentEvents = [baseEvent]
			const result = deleteRecurringEvent({
				targetEvent: targetInstance,
				currentEvents,
				scope: 'all',
			}).events

			expect(result).toHaveLength(0)
		})

		it('should only delete this instance (scope: this) and update exdates', () => {
			const baseEvent = createBaseRecurringEvent({ id: 'series-3' })
			const targetInstance: CalendarEvent = {
				...baseEvent,
				id: 'series-3_1',
				start: baseEvent.start.add(1, 'week'),
				end: baseEvent.end.add(1, 'week'),
				uid: 'series-3@ilamy.calendar',
				rrule: undefined,
			}

			const currentEvents = [baseEvent]
			const result = deleteRecurringEvent({
				targetEvent: targetInstance,
				currentEvents,
				scope: 'this',
			}).events

			expect(result).toHaveLength(1)
			expect(result[0].exdates).toContain(targetInstance.start.toISOString())
		})

		it('should report base + overrides in deleted for scope all', () => {
			const baseEvent = createBaseRecurringEvent({
				id: 'series-del-all',
				uid: 'series-del-all@ilamy.calendar',
			})
			const override: CalendarEvent = {
				...baseEvent,
				id: 'series-del-all_override',
				recurrenceId: '2025-01-13T10:00:00.000Z',
				rrule: undefined,
			}
			const currentEvents = [baseEvent, override]

			const { deleted, updated, added, events } = deleteRecurringEvent({
				targetEvent: baseEvent,
				currentEvents,
				scope: 'all',
			})

			expect(events).toHaveLength(0)
			expect(updated).toHaveLength(0)
			expect(added).toHaveLength(0)
			expect(deleted.map((e) => e.id)).toEqual([
				'series-del-all',
				'series-del-all_override',
			])
		})

		it('should report only the override in deleted for scope this when an override exists', () => {
			const baseEvent = createBaseRecurringEvent({
				id: 'series-del-this',
				uid: 'series-del-this@ilamy.calendar',
			})
			const occurrenceISO = '2025-01-13T10:00:00.000Z'
			const override: CalendarEvent = {
				...baseEvent,
				id: 'series-del-this_override',
				recurrenceId: occurrenceISO,
				rrule: undefined,
				start: dayjs(occurrenceISO),
				end: dayjs('2025-01-13T11:00:00.000Z'),
			}
			const currentEvents = [baseEvent, override]

			const { deleted, updated, added, events } = deleteRecurringEvent({
				targetEvent: override,
				currentEvents,
				scope: 'this',
			})

			expect(added).toHaveLength(0)
			expect(updated).toHaveLength(0)
			expect(deleted).toHaveLength(1)
			expect(deleted[0].id).toBe('series-del-this_override')
			expect(events).toHaveLength(1)
			expect(events[0].exdates).toContain(occurrenceISO)
		})

		it('should report empty deleted and base in updated for scope this on a generated instance', () => {
			const baseEvent = createBaseRecurringEvent({
				id: 'series-del-gen',
				uid: 'series-del-gen@ilamy.calendar',
			})
			const generatedInstance: CalendarEvent = {
				...baseEvent,
				id: 'series-del-gen_1',
				start: baseEvent.start.add(1, 'week'),
				end: baseEvent.end.add(1, 'week'),
				rrule: undefined,
			}
			const currentEvents = [baseEvent]

			const { deleted, updated } = deleteRecurringEvent({
				targetEvent: generatedInstance,
				currentEvents,
				scope: 'this',
			})

			expect(deleted).toHaveLength(0)
			expect(updated).toHaveLength(1)
			expect(updated[0].id).toBe('series-del-gen')
			expect(updated[0].exdates).toContain(
				generatedInstance.start.toISOString()
			)
		})
	})

	describe('updateRecurringEvent', () => {
		it('should update entire series (scope: all) when uid is missing', () => {
			const baseEvent = createBaseRecurringEvent({ id: 'series-4' })
			const targetInstance: CalendarEvent = {
				...baseEvent,
				id: 'series-4_1',
				start: baseEvent.start.add(1, 'week'),
				end: baseEvent.end.add(1, 'week'),
				uid: 'series-4@ilamy.calendar',
				rrule: undefined,
			}

			const currentEvents = [baseEvent]
			const result = updateRecurringEvent({
				targetEvent: targetInstance,
				updates: { title: 'New Title' },
				currentEvents,
				scope: 'all',
			}).events

			expect(result).toHaveLength(1)
			expect(result[0].title).toBe('New Title')
		})

		it('should report dropped detached overrides in deleted for scope all', () => {
			const baseEvent = createBaseRecurringEvent({
				id: 'series-edit-all',
				uid: 'series-edit-all@ilamy.calendar',
			})
			const detachedOverride: CalendarEvent = {
				...baseEvent,
				id: 'series-edit-all_override',
				recurrenceId: '2025-01-13T10:00:00.000Z',
				rrule: undefined,
			}
			const currentEvents = [baseEvent, detachedOverride]

			const { deleted, updated, events } = updateRecurringEvent({
				targetEvent: baseEvent,
				updates: { title: 'Reset Title' },
				currentEvents,
				scope: 'all',
			})

			expect(deleted).toHaveLength(1)
			expect(deleted[0].id).toBe('series-edit-all_override')
			expect(updated).toHaveLength(1)
			expect(updated[0].id).toBe('series-edit-all')
			expect(events.some((e) => e.id === 'series-edit-all_override')).toBe(
				false
			)
		})
	})

	describe('generateRecurringEvents', () => {
		it('should respect overrides when uid is missing from base but present in override', () => {
			const baseEvent = createBaseRecurringEvent({ id: 'series-5' })
			const overrideDate = baseEvent.start.add(1, 'week')
			const overrideEvent: CalendarEvent = {
				...baseEvent,
				id: 'series-5_override',
				start: overrideDate,
				end: overrideDate.add(1, 'hour'),
				title: 'Overridden Title',
				uid: 'series-5@ilamy.calendar',
				recurrenceId: overrideDate.toISOString(),
			}

			const currentEvents = [baseEvent, overrideEvent]
			const generated = generateRecurringEvents({
				event: baseEvent,
				currentEvents,
				startDate: baseEvent.start.subtract(1, 'day'),
				endDate: baseEvent.start.add(1, 'month'),
			})

			const overridden = generated.find((e) => e.start.isSame(overrideDate))
			expect(overridden?.title).toBe('Overridden Title')
		})
	})
})
