on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering for testing

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
